name: SPRING BACKEND DEPLOY TEMPLATE

on:
  workflow_call:
    inputs:
      SERVICE:
        description: '배포할 서비스의 이름 (e.g., e2e-test)'
        required: true
        type: string
    secrets:
      HOST:
        description: '배포 대상 서버의 호스트 주소'
        required: true
      PORT:
        description: '배포 대상 서버의 SSH 포트'
        required: true
      USER:
        description: '배포 대상 서버의 SSH 사용자 이름'
        required: true
      KEY:
        description: '서버 접속을 위한 Private SSH Key'
        required: true
      DOCKER_USER:
        description: 'Docker Hub 사용자 이름'
        required: true
      DOCKER_TOKEN:
        description: 'Docker Hub 액세스 토큰'
        required: true
      APP_YML:
        description: 'src/main/resources/application-prod.yml 파일에 쓰여질 내용'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 and Gradle Cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Create application.yml for production
        if: ${{ secrets.APP_YML != '' }}
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APP_YML }}" > src/main/resources/application-prod.yml

      - name: Build with Gradle
        run: ./gradlew clean bootJar --parallel --daemon --configuration-cache

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/${{ inputs.SERVICE }}:${{ github.sha }}
            ${{ secrets.DOCKER_USER }}/${{ inputs.SERVICE }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            # 환경 변수 설정
            IMAGE_NAME="${{ secrets.DOCKER_USER }}/${{ inputs.SERVICE }}"
            SERVICE_DIR="/opt/business_meeting/${{ inputs.SERVICE }}"
            
            echo ">>> [1] 서비스 디렉토리로 이동: ${SERVICE_DIR}"
            cd $SERVICE_DIR
            
            echo ">>> [2] 최신 Docker 이미지 pull"
            docker pull $IMAGE_NAME:latest
            
            echo ">>> [3] 기존 컨테이너 종료"
            docker compose down
            
            echo ">>> [4] 새 컨테이너 실행"
            docker compose up -d
            
            echo ">>> [5] 현재 배포된 버전을 제외한 모든 구버전 이미지 삭제"
            docker image prune -a -f --filter "label=org.opencontainers.image.revision!=${{ github.sha }}"
            
            echo ">>> [6] 실행 상태 확인"
            docker ps -a --filter "name=${{ inputs.SERVICE }}"