name: SPRING BACKEND DEPLOY TEMPLATE

on:
  workflow_call:
    inputs:
      SERVICE:
        required: true
        type: string
      HOST:
        required: true
        type: string
      PORT:
        required: true
        type: string
      USER:
        required: true
        type: string
    secrets:
      KEY:
        required: true
      DOCKER_USER:
        required: true
      DOCKER_TOKEN:
        required: true
      APP_YML:
        required: false


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Create application.yml (if provided)
        if: ${{ secrets.APP_YML != '' }}
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APP_YML }}" > src/main/resources/application-prod.yml

      - name: Build JAR
        run: ./gradlew clean bootJar --parallel --daemon --configuration-cache

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" |
          docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE="${{ secrets.DOCKER_USER }}/${{ inputs.SERVICE }}:latest"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

          docker build -t $IMAGE .

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE }}

      - name: Clean Local Docker Cache After Push
        run: docker system prune -af --volumes

      - name: Prepare Private Key
        run: |
          echo "${{ secrets.KEY }}" | sed 's/\r$//' > private_key
          chmod 600 private_key
          echo "PRIVATE_KEY<<EOF" >> $GITHUB_ENV
          cat private_key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ inputs.HOST }}
          port: ${{ inputs.PORT }}
          username: ${{ inputs.USER }}
          key: ${{ env.PRIVATE_KEY }}
          script: |
            cd /opt/business_meeting/${{ inputs.SERVICE }}

            echo "[1] 최신 이미지 Pull"
            docker pull ${{ env.IMAGE }}

            echo "[2] 기존 컨테이너 정리"
            docker compose down

            echo "[3] 새 컨테이너 실행"
            docker compose up -d

            echo "[4] 오래된 이미지 삭제"
            docker images "${{ secrets.DOCKER_USER }}/${{ inputs.SERVICE }}" \
              --format "{{.Repository}}:{{.Tag}} {{.ID}}" \
              | grep -v "latest" \
              | awk '{print $2}' \
              | xargs -r docker rmi -f

            echo "[5] Docker 시스템 정리"
            docker system prune -af --volumes

            echo "[6] 실행 상태 확인"
            docker ps
